from pathlib import Path

import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent
RESULTS_DIR = PROJECT_ROOT / "output" / "results"
FILTER_COLUMNS = {
    "Grade": "curso",
    "Curriculum axis": "eje",
    "Learning objective": "codigo_oa",
    "Skill": "habilidad_evaluada",
    "Model": "model",
}
SEARCH_COLUMNS = (
    "id",
    "texto_oa",
    "habilidad_evaluada",
    "contexto",
    "problem",
    "solution",
    "answer",
)


@st.cache_data
def load_results(path: str, modified_at: float) -> pd.DataFrame:
    del modified_at  # The modification time invalidates Streamlit's cache.
    return pd.read_csv(path, dtype=str, keep_default_na=False)


def filter_results(results: pd.DataFrame) -> pd.DataFrame:
    filtered = results
    search = st.sidebar.text_input("Search", placeholder="Problem, skill, context...")

    for label, column in FILTER_COLUMNS.items():
        if column not in filtered.columns:
            continue
        options = sorted(value for value in filtered[column].unique() if value)
        selected = st.sidebar.multiselect(label, options)
        if selected:
            filtered = filtered[filtered[column].isin(selected)]

    if "parse_error" in filtered.columns:
        status = st.sidebar.radio("Parse status", ("All", "Valid", "Errors"))
        has_error = filtered["parse_error"].str.strip().ne("")
        if status == "Valid":
            filtered = filtered[~has_error]
        elif status == "Errors":
            filtered = filtered[has_error]

    if search:
        columns = [column for column in SEARCH_COLUMNS if column in filtered.columns]
        matches = pd.Series(False, index=filtered.index)
        for column in columns:
            matches |= filtered[column].str.contains(search, case=False, regex=False)
        filtered = filtered[matches]

    return filtered


def show_result(row: pd.Series) -> None:
    item_id = row.get("id", "Untitled result")
    grade = row.get("curso", "")
    objective = row.get("codigo_oa", "")
    heading = " | ".join(value for value in (item_id, grade, objective) if value)

    with st.container(border=True):
        st.subheader(heading)
        metadata = " · ".join(
            value
            for value in (
                row.get("eje", ""),
                row.get("habilidad_evaluada", ""),
                row.get("contexto", ""),
            )
            if value
        )
        if metadata:
            st.caption(metadata)

        parse_error = row.get("parse_error", "").strip()
        if parse_error:
            st.error(f"Response parsing failed: {parse_error}")

        st.markdown("**Problem**")
        st.write(row.get("problem", "") or "No parsed problem available.")

        st.markdown("**Answer**")
        st.write(row.get("answer", "") or "No parsed answer available.")

        with st.expander("Solution and details"):
            st.markdown("**Solution**")
            st.write(row.get("solution", "") or "No parsed solution available.")

            for label, column in (
                ("Learning objective", "texto_oa"),
                ("Curricular conditions", "condiciones_curriculares"),
                ("Prompt", "prompt"),
                ("Raw response", "raw_response"),
            ):
                value = row.get(column, "")
                if value:
                    st.markdown(f"**{label}**")
                    st.write(value)


def main() -> None:
    st.set_page_config(
        page_title="MathGenBench-CL Results",
        page_icon=":material/calculate:",
        layout="wide",
    )
    st.title("MathGenBench-CL Results")
    st.caption(
        "Explore curriculum-aligned math word problems generated by language models."
    )

    result_files = sorted(RESULTS_DIR.glob("*.csv"))
    if not result_files:
        st.info(
            "No result files were found. Run the benchmark first to create a CSV in "
            "`output/results/`."
        )
        st.stop()

    selected_file = st.sidebar.selectbox(
        "Results file",
        result_files,
        format_func=lambda path: path.name,
    )
    results = load_results(str(selected_file), selected_file.stat().st_mtime)
    filtered = filter_results(results)

    error_count = (
        int(filtered["parse_error"].str.strip().ne("").sum())
        if "parse_error" in filtered.columns
        else 0
    )
    valid_count = len(filtered) - error_count
    metric_columns = st.columns(3)
    metric_columns[0].metric("Matching results", len(filtered))
    metric_columns[1].metric("Valid responses", valid_count)
    metric_columns[2].metric("Parsing errors", error_count)

    st.download_button(
        "Download filtered CSV",
        filtered.to_csv(index=False).encode("utf-8"),
        file_name=f"{selected_file.stem}-filtered.csv",
        mime="text/csv",
        disabled=filtered.empty,
    )

    if filtered.empty:
        st.warning("No results match the selected filters.")
        return

    page_size = st.sidebar.selectbox("Results per page", (10, 25, 50), index=0)
    page_count = max(1, (len(filtered) + page_size - 1) // page_size)
    page = st.sidebar.number_input("Page", min_value=1, max_value=page_count, value=1)
    start = (page - 1) * page_size
    st.caption(f"Page {page} of {page_count}")

    for _, row in filtered.iloc[start : start + page_size].iterrows():
        show_result(row)


if __name__ == "__main__":
    main()
